# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      dfinity-dependencies:
        patterns:
          - "@dfinity/*"
      svelte-dependencies:
        patterns:
          - "*svelte*"
          - "@sveltejs/*"
          - "floating-ui*"
          - "vite"
          - "typescript"
      development-tools:
        patterns:
          - "*eslint*"
          - "*prettier*"
      ui-tools:
        patterns:
          - "tailwindcss"
          - "autoprefixer"
          - "postcss*"
      misc:
        patterns:
          - "*"
        exclude-patterns:
          - "@dfinity/*"
          - "*svelte*"
          - "@sveltejs/*"
          - "*eslint*"
          - "*prettier*"
          - "typescript"
          - "vite"
          - "tailwindcss"
          - "autoprefixer"
          - "postcss*"
          - "floating-ui*"
