name: CD

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    name: deploy-dev
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Nostric
        run: |
          npm install
        continue-on-error: false

      - name: Install Mops
        run: |
          npm install -g ic-mops
        continue-on-error: false

      - uses: dfinity/setup-dfx@main
        with:
          dfx-version: auto
        env:
          DFX_IDENTITY_PEM: ${{ secrets.DFX_IDENTITY_PEM }}
      - run: |
          dfx start --clean --background
        continue-on-error: false

      - name: Dev environment deployment
        run: |
          cp canister_ids-dev.json canister_ids.json
          echo "${{ secrets.DFX_IDENTITY_PEM }}" > /home/runner/identity.pem
          dfx identity import action /home/runner/identity.pem
          dfx identity use action
          dfx identity set-wallet ${{ secrets.WALLET_CANISTER_ID }} --network ic
          dfx wallet balance --network ic
          dfx canister create internet_identity
          dfx build internet_identity
          dfx deploy --network ic --yes
        continue-on-error: false
